[package]
name = "smart_road"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["-C", "link-arg=-L/opt/homebrew/lib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
rand = "0.8.5"